<?php 
/**
 * Implements hook_menu_block_blocks().
 */
function cevoramenu_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
      'cevoramenu-1' => array(
          'menu_name'   => 'main-menu',
          'parent_mlid' => 0,
          'title_link'  => 0,
          'admin_title' => '',
          'level'       => 2,
          'follow'      => 0,
          'depth'       => 2,
          'expanded'    => 0,
          'sort'        => 0,
      ),
      'cevoramenu-2' => array(
          'menu_name'   => 'main-menu',
          'parent_mlid' => 0,
          'title_link'  => 0,
          'admin_title' => 'Hoofdmenu',
          'level'       => 1,
          'follow'      => 0,
          'depth'       => 1,
          'expanded'    => 0,
          'sort'        => 0,
      ),
  );
}
